### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by hepcat72** [i-net-software/SetupBuilder#42]
Hi,

Very inexperienced gradle user here, so the problem I'm having could just be me having mucked up things, but when I try to call `gradle deb`, I get:

```
* What went wrong:
Execution failed for task ':deb'.
> org.gradle.api.internal.file.copy.CopyActionExecuter.<init>(Lorg/gradle/internal/reflect/Instantiator;Lorg/gradle/internal/nativeintegration/filesystem/FileSystem;)V
```

I was using gradle 3.4.1 at the time, so I upgraded to the latest (4.1) and got the same error.  I saw that the documentation says 3.0 is the supported version, so I installed that and I get a different exception:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':deb'.
...
Caused by: java.lang.NullPointerException
```

Perhaps I'm trying to do the wrong thing?  I'm running in an Ubuntu virtual box.  I tried both `gradle deb` and `gradle rpm`.  Should either of those work on ubuntu?

Without SetupBuilder, I can build a working jar for my project just fine.  I've tried googling both errors and can't find anything that specifically relates to this issue.

Thanks,
Rob

**Comment by gamma** [comment]
Hi Rob, can you post a full log of the exception?

**Comment by hepcat72** [comment]
Here you go...

```
11:24:33.555 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] :deb FAILED
11:24:33.556 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :deb (Thread[Daemon worker,5,main]) completed. Took 0.055 secs.
11:24:33.556 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationWorkerRegistry] Worker root.5 completed (0 in use)
11:24:33.564 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Daemon worker,5,main]] finished, busy: 1.364 secs, idle: 0.057 secs
11:24:33.573 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:24:33.607 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
11:24:33.608 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:24:33.608 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
11:24:33.608 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':deb'.
11:24:33.608 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > java.lang.NullPointerException (no error message)
11:24:33.609 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:24:33.609 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
11:24:33.609 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':deb'.
11:24:33.609 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
11:24:33.610 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
11:24:33.610 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
11:24:33.610 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
11:24:33.615 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
11:24:33.615 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
11:24:33.616 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
11:24:33.616 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
11:24:33.616 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
11:24:33.616 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
11:24:33.616 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
11:24:33.616 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:74)
11:24:33.617 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:55)
11:24:33.617 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
11:24:33.617 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
11:24:33.617 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
11:24:33.617 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
11:24:33.617 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
11:24:33.617 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
11:24:33.618 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
11:24:33.635 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
11:24:33.635 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
11:24:33.635 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
11:24:33.635 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.Factories$1.create(Factories.java:22)
11:24:33.635 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
11:24:33.636 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
11:24:33.636 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
11:24:33.636 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
11:24:33.636 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
11:24:33.636 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
11:24:33.636 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
11:24:33.636 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
11:24:33.637 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
11:24:33.637 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
11:24:33.637 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
11:24:33.637 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
11:24:33.637 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
11:24:33.637 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
11:24:33.637 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
11:24:33.644 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:82)
11:24:33.644 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
11:24:33.644 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:59)
11:24:33.644 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
11:24:33.645 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:24:33.645 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:49)
11:24:33.645 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:24:33.645 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
11:24:33.645 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:24:33.645 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
11:24:33.645 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:24:33.645 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
11:24:33.646 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
11:24:33.646 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.util.Swapper.swap(Swapper.java:38)
11:24:33.646 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
11:24:33.646 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:24:33.646 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
11:24:33.646 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:24:33.646 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
11:24:33.649 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
11:24:33.649 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:24:33.650 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
11:24:33.650 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
11:24:33.650 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:24:33.650 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.HintGCAfterBuild.execute(HintGCAfterBuild.java:44)
11:24:33.654 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:24:33.654 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
11:24:33.654 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:240)
11:24:33.654 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
11:24:33.654 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
11:24:33.655 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
11:24:33.655 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
11:24:33.655 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.lang.Thread.run(Thread.java:748)
11:24:33.655 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.NullPointerException
11:24:33.655 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.inet.gradle.setup.unix.deb.DebBuilder.changeFilePermissionsTo644(DebBuilder.java:443)
11:24:33.655 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.inet.gradle.setup.unix.deb.DebBuilder.build(DebBuilder.java:66)
11:24:33.656 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.inet.gradle.setup.unix.deb.Deb.build(Deb.java:51)
11:24:33.656 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.inet.gradle.setup.AbstractTask.action(AbstractTask.java:89)
11:24:33.656 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:24:33.656 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:24:33.663 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:24:33.663 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.lang.reflect.Method.invoke(Method.java:498)
11:24:33.664 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
11:24:33.664 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:133)
11:24:33.664 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:126)
11:24:33.664 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:115)
11:24:33.664 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:623)
11:24:33.664 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:606)
11:24:33.664 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
11:24:33.669 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
11:24:33.669 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 71 more
11:24:33.670 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:24:33.670 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 
11:24:33.670 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED
11:24:33.670 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 
11:24:33.670 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] Total time: 16.515 secs
```

**Comment by hepcat72** [comment]
Still having this issue.  Any ideas on how to get around it?

**Comment by hepcat72** [comment]
Well... I couldn't figure out a work-around on linux and decided to move on to windows... I get the exact same error:

```
Execution failed for task ':msi'.
> org.gradle.api.internal.file.copy.CopyActionExecuter.<init>(...
...
Caused by: java.lang.NoSuchMethodError: org.gradle.api.internal.file.copy.CopyActionExecuter.<init>(...
```

Any ideas?  Could I be doing something wrong?  Could there be an unlisted dependency I don't have installed?

I'm working from a fresh windows 10 VM I just created.  In installed:

Java
Gradle
git
Wix Toolset

I then branched my project, added the setupbuilder stuff to the build.gradle file and ran `gradle msi`.  Here are the sections I added to my otherwise working gradle file (i.e. it creates mac .dmg/.app files using macAppBundle):

```
setupBuilder {
    vendor = 'test'
    application = 'Test'
    appIdentifier = 'Test'
    description = 'Test'
    version = '1.0'
    icons = 'src/main/resources/test.icns'
    licenseFile = 'LICENSES/LICENSE'
    bundleJre = 1.7
    mainClass = 'com.test.appname'
    mainJar = 'test.jar'
}

msi {
    
}
```

I put some placeholders in place of the name of our app.

**Comment by hepcat72** [comment]
I was looking at the source code and it looks like the line numbers in the stack trace correspond to setupbuilder version 1.7.0 even though I have version "1.8.0" in the plugin id.  I tried gradle version 2.14 to see if that works.  I also tried explicitly setting the setupbuilder version to 1.7.0.  I still get the same null pointer error each time.

**Comment by hepcat72** [comment]
Oh, uh... It's later versions of gradle that cause the NoSuchMethodError I referred to at the beginning of this issue.  After downgrading to the compatible gradle, I get the null pointer exception.

**Comment by hepcat72** [comment]
OK, well adding this to the build.gradle script got me past the null pointer exception:

```
    from ( 'build' ) {
        include 'libs/*.jar'
    }
```

Being a noob, I didn't understand what that was for and since nothing like that was needed for macAppBundle, I assumed it was unnecessary.  Doh!

Anyway, now I'm having a separate issue.  Do as you wish with this one.  I'll create another.

**Comment by gamma** [comment]
I honestly do not understand the connection ... but it is great that you were able to solve this problem.
