### ISSUE TITLE
Building msi on linux

### ISSUE THREAD

**Issue by JavaGrinko** [i-net-software/SetupBuilder#65]
Hello! Im trying to build msi on linux, but I get an error:
`Caused by: org.gradle.api.GradleException: Environment variable ProgramFiles not found.
	at com.inet.gradle.setup.msi.MsiBuilder.getToolPath(MsiBuilder.java:390)
	at com.inet.gradle.setup.msi.MsiBuilder.callWixTool(MsiBuilder.java:164)`
How can i fix this?

**Comment by Horcrux7** [comment]
SetupBuilder use tools of the target platform to build the native installer. For msi on Windows this is the WIX Toolset and other.

If the WIX Toolset works correctly under WINE on Linux has never tested before. I would not recommend it to try it. If you want do it you need to go a long way.

Which environment variables are use, can you see in the source code at https://github.com/i-net-software/SetupBuilder/blob/master/src/com/inet/gradle/setup/msi/MsiBuilder.java
The simplest is to the the environment variable "WIX".
