### ISSUE TITLE
wxs variables cannot be parsed

### ISSUE THREAD

**Issue by seanidzenga** [i-net-software/SetupBuilder#86]
I'm using a wxs template for building my msi and have been receiving this error: 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':msi'.
> class com.sun.org.apache.xerces.internal.dom.DeferredProcessingInstructionImpl cannot be cast to class org.w3c.dom.Element (com.sun.org.apache.xerces.internal.dom.DeferredProcessingInstructionImpl and org.w3c.dom.Element are in module java.xml of loader 'bootstrap')
```

The wxs spec provides the ability to define variables: https://wixtoolset.org/documentation/manual/v3/overview/preprocessor.html

An example similar to my wxs file:
```
<?xml version="1.0" encoding="UTF-8"?>
<?define foo = "foobar" ?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi" xmlns:util="http://schemas.microsoft.com/wix/UtilExtension">
    <Product Id="*" Name="$(var.foo)">
    </Product>
</Wix>
```

I assume it's the `foo` variable as the msi will build properly without it

the relevant section of my `build.gradle`

```
setupBuilder {
    vendor = "foobar"
    copyright = "Copyright ©"
    application = "foobar"
    appIdentifier = "foobar"
    version = "$version"
    licenseFile = "$projectDir/foobar/license.rtf"
    icons = ["$projectDir/msi/foobar.ico"]
}

msi {

    dependsOn = ["cleanDistributions", "compileJava", "copyLibs", "writePomProperties"]
    bannerBmp = "$projectDir/msi/banner.bmp"
    dialogBmp = "$projectDir/msi/dialog.bmp"
    wxsTemplate = "$projectDir/msi/foobar.wxs"
    languages = ["en", "fr"]
    minOS = 6.1
}
```

**Comment by Horcrux7** [comment]
Do you have a stacktrace of the exception?

**Comment by Horcrux7** [comment]
```
java.lang.ClassCastException: com.sun.org.apache.xerces.internal.dom.DeferredProcessingInstructionImpl cannot be cast to org.w3c.dom.Element
	at com.inet.gradle.setup.msi.WxsFileBuilder.build(WxsFileBuilder.java:115)
	at com.inet.gradle.setup.msi.MsiBuilder.build(MsiBuilder.java:67)
	at com.inet.gradle.setup.msi.Msi.build(Msi.java:101)
	at com.inet.gradle.setup.abstracts.AbstractTask.action(AbstractTask.java:100)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
```

**Comment by Horcrux7** [comment]
Please please try the snapshot version if it fix it with the follow code:

buildscript {
  repositories {
    maven { url 'https://jitpack.io' } // for snapshot
  }
  dependencies {
    classpath 'com.github.i-net-software:SetupBuilder:master-SNAPSHOT'
  }
}
apply plugin: "de.inetsoftware.setupbuilder"

**Comment by seanidzenga** [comment]
Sorry for the long delay in my response.

I gave the latest snapshot a try as well as the minor version upgrade 4.8.6 -> 4.8.7

I'm still getting the same result: `error CNDL0150 : Undefined preprocessor variable '$(var.ProductManufacturer)'`

Here's a full stacktrace:

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':msi'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:205)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:203)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.RuntimeException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe'' finished with non-zero exit value 150
        at com.inet.gradle.setup.abstracts.AbstractBuilder.exec(AbstractBuilder.java:163)
        at com.inet.gradle.setup.abstracts.AbstractBuilder.exec(AbstractBuilder.java:76)
        at com.inet.gradle.setup.abstracts.AbstractBuilder.exec(AbstractBuilder.java:65)
        at com.inet.gradle.setup.msi.MsiBuilder.callWixTool(MsiBuilder.java:166)
        at com.inet.gradle.setup.msi.MsiBuilder.candle(MsiBuilder.java:186)
        at com.inet.gradle.setup.msi.MsiBuilder.build(MsiBuilder.java:71)
        at com.inet.gradle.setup.msi.Msi.build(Msi.java:103)
        at com.inet.gradle.setup.abstracts.AbstractTask.action(AbstractTask.java:101)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:727)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:694)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:568)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:553)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:536)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:276)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:265)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:63)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:153)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:67)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:41)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:192)
        ... 30 more
Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe'' finished with non-zero exit value 150
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:417)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:38)
        at com.inet.gradle.setup.abstracts.AbstractBuilder.exec(AbstractBuilder.java:160)
        ... 102 more
```

**Comment by Horcrux7** [comment]
This error must be related to your custom template. The error come from the candle.exe tool. Look into the generated *.wxs file to find the cause of the error. SetupBuilder does not handle any variables in the *.wxs file.

**Comment by seanidzenga** [comment]
That's a shame, is there maybe a way to add custom variables to SetupBuilder? or perhaps it could be considered for a feature request?

The way I'm handling the preprocessor vars now is to pass them to candle through a `commandLine` call like so:

```
task wix(type:Exec) {

    dependsOn = ["copyJDK", "copyProductWxs", "heatLib", "heatConfig", "heatJDK"]

    workingDir "$projectDir"

    /* compile Product.wxs */
    commandLine "candle", 
        "-dProductName=" + rootProject.name, 
        "-dProductManufacturer=" + project.manufacturer, 
        "-dUpgradeCode=" + project.upgradeCode, 
        '-dCommitRefName="foo"',  // TODO get commit reference variable
        "-dPipeline=\"bar\"", // TODO - get pipeline variable
        "-dProductVersion=\"$version.0\"",
        "-dLibDirectory=\"$buildDir/appassembler/windows/lib\"",
        "-dConfigDirectory=\"$buildDir/appassembler/windows/config\"",
        "-dJDKDirectory=\"$buildDir/appassembler/windows/jdk\"",
        "-dBuildDirectory=\"$buildDir\"",
        "-out", "$buildDir/wix/", 
        "$buildDir/wix/Product.wxs",
        "$buildDir/wix/Lib.wxs",
        "$buildDir/wix/Config.wxs",
        "$buildDir/wix/JDK.wxs"
}
```
This might not be a major feature everyone uses in wix but it's one my team does, more info here: https://wixtoolset.org/documentation/manual/v3/overview/preprocessor.html

**Comment by Horcrux7** [comment]
For some of this parameters there are already a API in SetupBuilder. And this API is platform independent. The main target of the SetupBuilder project. Creating native setups for Java applications on different OS platforms.

If you want use a special WIX features that the generic SetupBuilder can't handle then there you can set the base template. Instead an extra API for some command line switches, the simplest solution is to create a patched template file. It is very simple to do this in the calling Gradle script.

If you want work on such a low level that you want set command line switches of the intermediate tools then I think the SetupBuilder is not the real tool for you.

**Comment by seanidzenga** [comment]
That's fair, thanks for the help.
